### PR TITLE
create set_latency_start and set_latency_end for Python

### PR DESCRIPTION
**Pull request by JoseGuzman**
For consistency with the other pairs of cursors (base, peak and decay),` stf.get_latency_start()` and `stf.get_latency_end()` should be included. In addition to setting the  ursor position, these functions also change the latency mode to "manual", and update the latency measure (`stf.get_latency()`) immediately.

### CODE REVIEW

**Comment by neurodroid** [comment]
There's now also an oo way of accessing the cursors (stf.peak.*,
stf.base.*). Would it be possible to implement that for the latency
cursors as well?

**Comment by JoseGuzman** [comment]
Yes, I'll do it. We will have to document it too. Until now, everything is explained for  stf.get_peak_start/end()-like functions

**Comment by JoseGuzman** [comment]
OO approach for latency cursors was tested for the following functions:

```
stf.latency.cursor_time # getter
stf.latency.cursor_index # getter
stf.latency.cursor_time = (100,200) # setter
stf.latency.cursor_index = (2000, 4000) # setter
stf.latency.value # getter
```

**Comment by JoseGuzman** [comment]
I would suggest, to avoid unnecessary misunderstandings, to always compute the latencies between the peak cursors. Several users are confused by the fact that one can select between latencies within the peaks and not. Moreover, by only having the the option to select latencies between cursors, we are sure that the computations are correct. This is now described more clearly in the documentation.

**Pull request merged**
