### PR TITLE
BF: provide wx-config opts if wx-config present

### PR DESCRIPTION
**Pull request by yarikoptic**
ref: #70

### CODE REVIEW

**Comment by neurodroid** [comment]
Thanks @yarikoptic ! I'm probably getting this wrong, but executing `hash wx-config 2>/dev/null && echo '--with-wx-config="wx-config --toolkit=gtk3"' || echo ''` results in `--with-wx-config="wx-config --toolkit=gtk3"` on both a system with wx-gtk3 (bionic) as well as without wx-gtk3 (xenial). Shouldn't it only result in `--with-wx-config="wx-config --toolkit=gtk3"` if wx-gtk3 is present?

**Comment by neurodroid** [comment]
PS: On xenial, `wx-config` is present, but executing `wx-config --toolkit=gtk3` results in an error.

**Comment by yarikoptic** [comment]
well, then what about this one?  ;-)

**Comment by neurodroid** [comment]
Thanks @yarikoptic, this seems to do the trick (by some shell magic hidden to me)

**Comment by yarikoptic** [comment]
oh, there is no magic whatsoever!!!  `&&` is an `and` and `||` is `or`, or in other words I am doing "if... then ... else ...", so it is "if command succeeds; then echo command; else echo nothing"

**Pull request merged**
